# permissions to do viewer partitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: partition-viewer-role
rules:
- apiGroups:
  - yunikorn.incubator.apache.org
  resources:
  - partitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - yunikorn.incubator.apache.org
  resources:
  - partitions/status
  verbs:
  - get
